AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Solution Helper resources.
Parameters:
  StackName:
    Description: |
      Used as a prefix to name all stack resources.
      Should be root stack's name if this is a nested stack.
    Type: String
  S3BucketName:
    Description: Amazon S3 Bucket used to store datasets and schemas.
    Type: String
  SolutionsS3BucketName:
    Description: Amazon S3 Bucket containing solutions.
    Type: String
  ECRRepository:
    Description: Amazon ECR Repository used to store Amazon SageMaker images.
    Type: String
Resources:
  SolutionAssistant:
    Type: "Custom::SolutionAssistant"
    Properties:
      ServiceToken: !GetAtt SolutionAssistantLambda.Arn
      StackName: !Ref StackName
      S3BucketName: !Ref S3BucketName
      SolutionsS3BucketName: !Ref SolutionsS3BucketName
      ECRRepository: !Ref ECRRepository
  SolutionAssistantLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "lambda_function.handler"
      FunctionName: !Sub "${StackName}-solution-assistant"
      Role: !GetAtt SolutionAssistantLambdaRole.Arn
      Runtime: "python3.8"
      Code: ./src
      Timeout : 60
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W3002
            reason: Using cloudformation package command.
  SolutionAssistantLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: ReadFromSolutionsS3Bucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub "arn:aws:s3:::${SolutionsS3BucketName}"
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${SolutionsS3BucketName}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub "arn:aws:s3:::${S3BucketName}"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:AbortMultipartUpload
              Resource:
                - !Sub "arn:aws:s3:::${S3BucketName}/*"
            - Effect: Allow
              Action:
                - sagemaker:DeleteModel
              Resource:
                - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:model/*"
            - Effect: Allow
              Action:
                - sagemaker:DeleteEndpointConfig
              Resource:
                - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint-config/*"
            - Effect: Allow
              Action:
                - sagemaker:DeleteEndpoint
              Resource:
                - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/*"
                - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint-config/*"
            - Effect: Allow
              Action:
                - ecr:DescribeImages
                - ecr:BatchDeleteImage
              Resource:
                - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRRepository}"
